image: fedora/latest
oauth: git.sr.ht/REPOSITORIES:RW git.sr.ht/PROFILE:RO
packages:
  - hut
  - swig
  - python3
  - python3-devel
  - python3-pip
  - openssl-devel
  - openssl-devel-engine
  - openssl
  - crypto-policies-scripts
  - python3-setuptools
  - python3-twisted
  - python3-pexpect
  - python3-docutils
environment:
  CFLAGS: -pthread -Wno-unused-result -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -D_GNU_SOURCE -fwrapv
sources:
  - https://git.sr.ht/~mcepl/m2crypto
secrets:
  - nickserv_pass
tasks:
  - build: |
     cd m2crypto
     export PATH=$PATH:$HOME/.local/bin
     python3 -mpip install --user -r dev-requirements.txt
     python3 -mpip wheel --verbose  --no-cache-dir --no-clean --no-build-isolation --wheel-dir dist/ --editable .
     find . -name \*.c
     find . -name \*.whl -o -name \*.tar.gz
     mkdir -p shadowing/sys && touch shadowing/sys/types.h
     python3 -mpip install -v --upgrade --target $(readlink -f build/lib.*) --no-compile --ignore-installed --no-deps --no-index dist/m2crypto*.whl
  - test: |
     cd m2crypto
     sudo update-crypto-policies --set LEGACY
     PYTHONPATH=$(readlink -f build/lib.*) python3 -munittest -b -v tests.alltests.suite
     [ -n "$GIT_REF" ] && REASON="$JOB_ID ($GIT_REF)"
     [ -n "$PATCHSET_URL" ] && REASON="$JOB_ID ($PATCHSET_URL)"
     set +x
     # .builds/irc-send mcepl build-bot m2crypto "sourcehut build $REASON finished with the result $? ($JOB_URL)." "$(cat ~/.irc_pass)"
     set -x
  - readme: |
     cd m2crypto
     printf "GIT_REF: %s\n" "${GIT_REF}"
     python3 -mdocutils --strict README.rst >/dev/null
     case $GIT_REF in
        *master*)
            python3 -mdocutils README.rst \
              | sed -n '1,/<body>/d;/<\/body>/q;p' \
              |hut git -r m2crypto update --readme -
        ;;
     esac
artifacts:
  - m2crypto/src/SWIG/_m2crypto_wrap.c
  # https://is.gd/Z5VJlI
  # - pygn/dist/pygn-*.tar.gz
  # - pygn/dist/pygn-*.whl
