image: fedora/latest
packages:
  - swig
  - python3
  - python3-devel
  - python3-pip
  - openssl-devel
  - openssl
  - python3-setuptools
  - python3-twisted
sources:
  - https://git.sr.ht/~mcepl/m2crypto
tasks:
  - build: |
     cd m2crypto
     export PATH=$PATH:$HOME/.local/bin
     python3 -mpip install --user -r dev-requirements.txt
     python3 -mbuild .
     find . -name \*.whl -o -name \*.tar.gz
     python3 -mpip install -v --upgrade --target $(readlink -f build/lib.*) --no-compile --ignore-installed --no-deps --no-index dist/M2Crypto*.whl
  - test: |
     cd m2crypto
     PYTHONPATH=$(readlink -f build/lib.*) python3 -munittest -b -v tests.alltests.suite
artifacts:
  # https://is.gd/Z5VJlI
  # - pygn/dist/pygn-*.tar.gz
  # - pygn/dist/pygn-*.whl
