version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - swig
  tools:
    python: "3.12"

sphinx:
  configuration: doc/conf.py

python:
   install:
     - requirements: doc/requirements.txt
       # The autodoc generation needs to be able to import the M2Crypto module.
       # Since this is only possible when M2Crypto is fully installed (after
       # the swig bindings have been generated), we manually install it here.
     - method: pip
       path: .
